name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    env:
      PORT: 3000
      MONGODB_URL: mongodb+srv://innovaturetechenginneers:12345@cluster0.v5xdh.mongodb.net/collegepick
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
      SMTP_HOST: email-server
      SMTP_PORT: 587
      SMTP_USERNAME: email-server-username
      SMTP_PASSWORD: email-server-password
      EMAIL_FROM: support@yourapp.com
    steps:
    - uses: actions/checkout@v4  # This step fetches your code (including package-lock.json)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci  # Will work if package-lock.json exists in the repo
